use std::path::PathBuf;

use clap::Parser;

use tree_sitter_struct::{
    generate, read_from_file, NameOverrideStep, NameOverrideStepChoiceMember,
    NameOverrideStepRuleName, NameOverrideStepSeqMember,
};

fn main() {
    let args = Args::parse();

    let grammar_json = read_from_file(&args.grammar_json_filename).unwrap();
    // println!("grammar_json: {grammar_json:#?}");
    generate(
        &grammar_json,
        &args.language,
        &[
            (";".to_owned(), "semicolon".to_owned()),
            ("(".to_owned(), "left_paren".to_owned()),
            (")".to_owned(), "right_paren".to_owned()),
            ("[".to_owned(), "left_square_bracket".to_owned()),
            ("]".to_owned(), "right_square_bracket".to_owned()),
            ("{".to_owned(), "left_curly_bracket".to_owned()),
            ("}".to_owned(), "right_curly_bracket".to_owned()),
            ("=>".to_owned(), "fat_arrow".to_owned()),
            ("->".to_owned(), "skinny_arrow".to_owned()),
            (":".to_owned(), "colon".to_owned()),
            ("::".to_owned(), "colon_colon".to_owned()),
            ("$".to_owned(), "dollar_sign".to_owned()),
            ("@".to_owned(), "at_sign".to_owned()),
            ("#".to_owned(), "pound_sign".to_owned()),
            ("'".to_owned(), "single_quote".to_owned()),
            ("\"".to_owned(), "double_quote".to_owned()),
            ("_".to_owned(), "underscore".to_owned()),
            (",".to_owned(), "comma".to_owned()),
            (".".to_owned(), "dot".to_owned()),
            ("..".to_owned(), "dot_dot".to_owned()),
            ("..=".to_owned(), "dot_dot_equals".to_owned()),
            ("...".to_owned(), "dot_dot_dot".to_owned()),
            ("=".to_owned(), "equals_sign".to_owned()),
            ("==".to_owned(), "equals_equals".to_owned()),
            ("+".to_owned(), "plus_sign".to_owned()),
            ("+=".to_owned(), "plus_equals".to_owned()),
            ("-".to_owned(), "minus_sign".to_owned()),
            ("-=".to_owned(), "minus_equals".to_owned()),
            ("*".to_owned(), "asterisk".to_owned()),
            ("*=".to_owned(), "asterisk_equals".to_owned()),
            ("*/".to_owned(), "asterisk_forward_slash".to_owned()),
            ("?".to_owned(), "question_mark".to_owned()),
            ("/".to_owned(), "forward_slash".to_owned()),
            ("/=".to_owned(), "forward_slash_equals".to_owned()),
            ("/*".to_owned(), "forward_slash_asterisk".to_owned()),
            ("//".to_owned(), "forward_slash_forward_slash".to_owned()),
            ("\\".to_owned(), "back_slash".to_owned()),
            ("%".to_owned(), "percent_sign".to_owned()),
            ("%=".to_owned(), "percent_equals".to_owned()),
            ("^".to_owned(), "caret".to_owned()),
            ("^=".to_owned(), "caret_equals".to_owned()),
            ("!".to_owned(), "exclamation_point".to_owned()),
            ("!=".to_owned(), "exclamation_equals".to_owned()),
            ("&".to_owned(), "ampersand".to_owned()),
            ("&=".to_owned(), "ampersand_equals".to_owned()),
            ("&&".to_owned(), "ampersand_ampersand".to_owned()),
            ("|".to_owned(), "bar".to_owned()),
            ("|=".to_owned(), "bar_equals".to_owned()),
            ("||".to_owned(), "bar_bar".to_owned()),
            ("<".to_owned(), "left_caret".to_owned()),
            ("<=".to_owned(), "left_caret_equals".to_owned()),
            ("<<".to_owned(), "left_caret_left_caret".to_owned()),
            ("<<=".to_owned(), "left_caret_left_caret_equals".to_owned()),
            (">".to_owned(), "right_caret".to_owned()),
            (">=".to_owned(), "right_caret_equals".to_owned()),
            (">>".to_owned(), "right_caret_right_caret".to_owned()),
            (
                ">>=".to_owned(),
                "right_caret_right_caret_equals".to_owned(),
            ),
            ("as".to_owned(), "as".to_owned()),
            ("async".to_owned(), "async".to_owned()),
            ("await".to_owned(), "await".to_owned()),
            ("b".to_owned(), "b".to_owned()),
            ("block".to_owned(), "block".to_owned()),
            ("break".to_owned(), "break".to_owned()),
            ("bool".to_owned(), "bool".to_owned()),
            ("char".to_owned(), "char".to_owned()),
            ("const".to_owned(), "const".to_owned()),
            ("continue".to_owned(), "continue".to_owned()),
            ("crate".to_owned(), "crate".to_owned()),
            ("default".to_owned(), "default".to_owned()),
            ("dyn".to_owned(), "dyn".to_owned()),
            ("else".to_owned(), "else".to_owned()),
            ("enum".to_owned(), "enum".to_owned()),
            ("expr".to_owned(), "expr".to_owned()),
            ("expr_2021".to_owned(), "expr_2021".to_owned()),
            ("extern".to_owned(), "extern".to_owned()),
            ("false".to_owned(), "false".to_owned()),
            ("fn".to_owned(), "fn".to_owned()),
            ("for".to_owned(), "for".to_owned()),
            ("f32".to_owned(), "f32".to_owned()),
            ("f64".to_owned(), "f64".to_owned()),
            ("gen".to_owned(), "gen".to_owned()),
            ("ident".to_owned(), "ident".to_owned()),
            ("if".to_owned(), "if".to_owned()),
            ("impl".to_owned(), "impl".to_owned()),
            ("in".to_owned(), "in".to_owned()),
            ("isize".to_owned(), "isize".to_owned()),
            ("item".to_owned(), "item".to_owned()),
            ("i8".to_owned(), "i8".to_owned()),
            ("i16".to_owned(), "i16".to_owned()),
            ("i32".to_owned(), "i32".to_owned()),
            ("i64".to_owned(), "i64".to_owned()),
            ("i128".to_owned(), "i128".to_owned()),
            ("let".to_owned(), "let".to_owned()),
            ("lifetime".to_owned(), "lifetime".to_owned()),
            ("literal".to_owned(), "literal".to_owned()),
            ("loop".to_owned(), "loop".to_owned()),
            ("macro_rules!".to_owned(), "macro_rules".to_owned()),
            ("match".to_owned(), "match".to_owned()),
            ("meta".to_owned(), "meta".to_owned()),
            ("mod".to_owned(), "mod".to_owned()),
            ("move".to_owned(), "move".to_owned()),
            ("mut".to_owned(), "mut".to_owned()),
            ("pat".to_owned(), "pat".to_owned()),
            ("pat_param".to_owned(), "pat_param".to_owned()),
            ("path".to_owned(), "path".to_owned()),
            ("pub".to_owned(), "pub".to_owned()),
            ("raw".to_owned(), "raw".to_owned()),
            ("ref".to_owned(), "ref".to_owned()),
            ("return".to_owned(), "return".to_owned()),
            ("self".to_owned(), "self".to_owned()),
            ("static".to_owned(), "static".to_owned()),
            ("stmt".to_owned(), "stmt".to_owned()),
            ("str".to_owned(), "str".to_owned()),
            ("struct".to_owned(), "struct".to_owned()),
            ("super".to_owned(), "super".to_owned()),
            ("trait".to_owned(), "trait".to_owned()),
            ("true".to_owned(), "true".to_owned()),
            ("try".to_owned(), "try".to_owned()),
            ("tt".to_owned(), "tt".to_owned()),
            ("ty".to_owned(), "ty".to_owned()),
            ("type".to_owned(), "type".to_owned()),
            ("union".to_owned(), "union".to_owned()),
            ("unsafe".to_owned(), "unsafe".to_owned()),
            ("use".to_owned(), "use".to_owned()),
            ("usize".to_owned(), "usize".to_owned()),
            ("u8".to_owned(), "u8".to_owned()),
            ("u16".to_owned(), "u16".to_owned()),
            ("u32".to_owned(), "u32".to_owned()),
            ("u64".to_owned(), "u64".to_owned()),
            ("u128".to_owned(), "u128".to_owned()),
            ("vis".to_owned(), "vis".to_owned()),
            ("where".to_owned(), "where".to_owned()),
            ("while".to_owned(), "while".to_owned()),
            ("yield".to_owned(), "yield".to_owned()),
        ]
        .into_iter()
        .collect(),
        &[NameOverrideStepRuleName {
            rule_name: "macro_definition".to_owned(),
            steps: vec![NameOverrideStepSeqMember {
                index: 2,
                steps: vec![
                    NameOverrideStep::Override("body".to_owned()),
                    NameOverrideStepChoiceMember {
                        index: 0,
                        steps: vec![NameOverrideStep::Override("paren".to_owned())],
                    }
                    .into(),
                    NameOverrideStepChoiceMember {
                        index: 1,
                        steps: vec![NameOverrideStep::Override("square_bracket".to_owned())],
                    }
                    .into(),
                    NameOverrideStepChoiceMember {
                        index: 2,
                        steps: vec![NameOverrideStep::Override("curly_bracket".to_owned())],
                    }
                    .into(),
                ],
            }
            .into()],
        }
        .into()],
    );
}

#[derive(Parser)]
struct Args {
    pub grammar_json_filename: PathBuf,
    pub language: String,
}
